### PR TITLE
Gradle 6 support

### PR DESCRIPTION
**Pull request by halfninja**
Gradle 6 doesn't like you creating a task with overwrite:true if the task doesn't already exist. I don't think the task would already exist so the fix here is simply to stop passing overwrite:true.

Also a few other tweaks to resolve some warnings for Gradle 7 - the is one remaining about the use of the maven plugin but I don't really know what I'm doing there so leaving it.

### CODE REVIEW

**Review by james-bryant — APPROVED** [review]
Looks good.  Thanks you!

**Comment by james-bryant** [comment]
Are you able to execute the test after your changes?  I'm having trouble
running it.

**Comment by halfninja** [comment]
Hey @james-bryant, yep it is working okay for me locally and [GitHub is running it okay ](https://github.com/james-bryant/gradle-aspectj/commit/773a883f4b78b6c00fff429330f8576a865e5ca1/checks?check_suite_id=316778867). I'm doing `./gradlew clean test -PossrhUsername=x -PossrhPassword=x` (the fake properties specified here just because I don't have any real credentials and they're not needed for the test)

**Comment by james-bryant** [comment]
Yea, something must be off with my local environment.  I see the test works
fine on GitHub as well.  Thanks for setting that up BTW.  And thanks again
for your contribution.  I don't have as much time to keep things up to date
lately.
I've gone ahead and published version 2.5 with your changes (
https://search.maven.org/artifact/net.uberfoo.gradle/gradle-aspectj/2.5/jar
).

**Pull request merged**
